---
# Vagrant user config should be handled by jtyr.vagrant_user (or similar)

# Fix slow DNS.
# from: geerlingguy.packer-rhel
# see: https://github.com/mitchellh/vagrant/issues/1172
- name: Fix slow DNS (adapted from Bento).
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present
  register: slow_dns_fix
  tags:
    - vagrant_slow_dns_fix

# from: samdoran.packer-rhel
- name: Restart network service.
  service: name=network state=restarted
  when: slow_dns_fix | changed

# SSH daemon configuration.
# from: geerlingguy.packer-rhel
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^UseDNS', line: 'UseDNS no' }
    - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }
  notify: restart sshd
  tags:
    - vagrant_ssh

# adapted from: https://github.com/CentOS/sig-cloud-instance-build/blob/5162d86c01/vagrant/centos7.ks
- name: Prevent sshd from doing reverse DNS lookups (adapted from sig-cloud-instance-build).
  blockinfile:
    dest: /etc/sysconfig/sshd
    state: present
    insertafter: EOF
    block: |
      # Decrease connection time by preventing reverse DNS lookups
      # (see https://lists.centos.org/pipermail/centos-devel/2016-July/014981.html
      #  and man sshd for more information)
      OPTIONS="-u0"
  notify: restart sshd
  tags:
    - vagrant_ssh
